language: node_js
notifications:
  email: false
node_js:
  - 'node'
  - '8'
  - '7'
  - '6'
after_success:
  - npm run coveralls:travis
  - sh ./sh/prepublish.sh && sh ./sh/publish.sh
branches:
  except:
    - /^v\d+\.\d+\.\d+$/