blank_issues_enabled: false
slack_discussions:
  - name: 💬 Question or help request (Slack)
    url: https://api.tsed.io/rest/slack/typedproject/tsed
    about: You want to ask a question or discuss with other community members
gitter_discussions:
  - name: 💬 Question or help request (Gitter deprecated)
    url: https://gitter.im/Tsed-io/Community
    about: You want to ask a question or discuss with other community members
